# $Id: Makefile 315 2008-11-14 16:12:15Z phf $
CFLAGS=-O0 -std=c99 -Wall -Wextra # try -O3 for fun...

ALL=compare_mod_and minunit_example get_set_progname sizeof bitsets loweror fsize #args

all: $(ALL)

clean:
	rm -rf *.o $(ALL)
